// Prop definition
export * from './prop-def';

// Individual props
export * from './as-child.prop';
export * from './color.prop';
export * from './gap.props';
export * from './height.props';
export * from './high-contrast.prop';
export * from './layout.props';
export * from './leading-trim.prop';
export * from './margin.props';
export * from './padding.props';
export * from './radius.prop';
export * from './text-align.prop';
export * from './text-wrap.prop';
export * from './truncate.prop';
export * from './weight.prop';
export * from './width.props';

// Component props
// export * from '../components/alert-dialog.props.js';
// export * from '../components/avatar.props.js';
// export * from '../components/badge.props.js';
// export * from '../components/blockquote.props.js';
// export * from '../components/box.props.js';
// export * from '../components/button.props.js';
// export * from '../components/callout.props.js';
// export * from '../components/card.props.js';
// export * from '../components/checkbox-cards.props.js';
// export * from '../components/checkbox-group.props.js';
// export * from '../components/checkbox.props.js';
// export * from '../components/code.props.js';
// export * from '../components/container.props.js';
// export * from '../components/context-menu.props.js';
// export * from '../components/data-list.props.js';
// export * from '../components/dialog.props.js';
// export * from '../components/dropdown-menu.props.js';
// export * from '../components/em.props.js';
// export * from '../components/flex.props.js';
// export * from '../components/grid.props.js';
// export * from '../components/heading.props.js';
// export * from '../components/hover-card.props.js';
// export * from '../components/icon-button.props.js';
// export * from '../components/inset.props.js';
// export * from '../components/kbd.props.js';
// export * from '../components/link.props.js';
// export * from '../components/popover.props.js';
// export * from '../components/progress.props.js';
// export * from '../components/quote.props.js';
// export * from '../components/radio.props.js';
// export * from '../components/radio-cards.props.js';
// export * from '../components/radio-group.props.js';
// export * from '../components/scroll-area.props.js';
// export * from '../components/section.props.js';
// export * from '../components/segmented-control.props.js';
// export * from '../components/select.props.js';
// export * from '../components/separator.props.js';
// export * from '../components/skeleton.props.js';
// export * from '../components/slider.props.js';
// export * from '../components/spinner.props.js';
// export * from '../components/strong.props.js';
// export * from '../components/switch.props.js';
// export * from '../components/tab-nav.props.js';
// export * from '../components/table.props.js';
// export * from '../components/tabs.props.js';
// export * from '../components/text-area.props.js';
// export * from '../components/text-field.props.js';
// export * from '../components/text.props.js';
// export * from '../components/theme.props.js';
// export * from '../components/tooltip.props.js';
